from sqla_lite import table, Id, Size, Decimal, DateFormat, repository, configure_database
from sqla_lite.core import Base
from sqlalchemy import create_engine
from datetime import datetime

# Your Class in Spring Boot style (Pythonized)!
@table("employee_roles")
class EmployeeRole:
    # First part of the composite primary key
    employee_id: int = Id()
    # Second part of the composite primary key (String with specific Size!)
    role_name: str = Id(size=50)
    
    # Just a regular attribute
    assigned_date: datetime

# Your Repository!
@repository(EmployeeRole)
class EmployeeRoleRepository:
    pass

# Testing with in-memory SQLite
if __name__ == "__main__":
    print(f"Class Generated by Decorator: {EmployeeRole}")
    print(f"Repository Generated: {EmployeeRoleRepository}")
    
    engine = create_engine("sqlite:///:memory:", echo=False)
    # DDL command that creates the table in the database
    Base.metadata.create_all(engine)
    
    # Configure it once at the start of your application
    configure_database(engine)

    # Now you can just use the repository!
    repo = EmployeeRoleRepository()
    
    new_role = EmployeeRole(
        employee_id=101, 
        role_name="Software Engineer",
        assigned_date=datetime.now()
    )
    
    # Save the entity (Handles sessions automatically)
    repo.save(new_role)
    
    # Query data using the repository!
    # With *args support, you don't need tuples for composite keys!
    saved_role = repo.get(101, "Software Engineer")
    
    print(f"\nUser Successfully Saved via Repository!")
    print(f"Composite Key -> Employee ID: {saved_role.employee_id} | Role: {saved_role.role_name}")
    print(f"Native Python Type (Assigned At): {saved_role.assigned_date}")
